#Uso da biblioteca Pandas

In [2]:
import pandas as pd

In [3]:
dados = pd.read_excel("/content/drive/MyDrive/programaria/Experiência.xlsx")

In [4]:
dados.tail()

,ID,IDADE,FAIXA IDADE,GENERO,COR/RACA/ETNIA,PCD,EXPERIENCIA_PROFISSIONAL_PREJUDICADA,PREJUDICA?,ASPECTOS_PREJUDICADOS,VIVE_NO_BRASIL,...,NUMERO DE FUNCIONARIOS,GESTOR?,CARGO COMO GESTOR,CARGO ATUAL,NIVEL,Novo nível,FAIXA SALARIAL,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?,COMPUTAÇÃO?
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,26.0,25-29,Masculino,Branca,Não,NaN,False,NaN,True,...,Acima de 3.000,False,NaN,Analista de Dados/Data Analyst,Pleno,Pleno,de R$ 4.001/mês a R$ 6.000/mês,de 3 a 4 anos,de 7 a 10 anos,NaN
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30.0,30-34,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,False,NaN,True,...,de 51 a 100,False,NaN,Engenheiro de Dados/Arquiteto de Dados/Data En...,Pleno,Pleno,de R$ 3.001/mês a R$ 4.000/mês,de 1 a 2 anos,Não tive experiência na área de TI/Engenharia ...,NaN
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,29.0,25-29,Masculino,Branca,Não,NaN,False,NaN,True,...,de 101 a 500,True,Gerente/Head,NaN,NaN,Pleno,de R$ 16.001/mês a R$ 20.000/mês,de 4 a 6 anos,Não tive experiência na área de TI/Engenharia ...,NaN
4269,00xu7yujd7s57emj00xu7y0c3njix3de,NaN,17-21,Masculino,Branca,Não,NaN,False,NaN,True,...,de 1.001 a 3.000,False,NaN,Outra Opção,Júnior,PESSOA GESTORA,Menos de R$ 1.000/mês,Menos de 1 ano,Não tive experiência na área de TI/Engenharia ...,NaN
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,24.0,22-24,Masculino,Branca,Não,NaN,False,NaN,True,...,de 501 a 1.000,False,NaN,Analista de Dados/Data Analyst,Júnior,Júnior,de R$ 3.001/mês a R$ 4.000/mês,de 1 a 2 anos,Não tive experiência na área de TI/Engenharia ...,NaN

In [5]:
dados.shape

(4271, 29)

In [6]:
len(dados)

4271

In [9]:
dados.columns

Index(['ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA', 'PCD',
       'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'PREJUDICA?',
       'ASPECTOS_PREJUDICADOS', 'VIVE_NO_BRASIL', 'ESTADO ONDE MORA',
       'UF ONDE MORA', 'REGIAO ONDE MORA', 'MUDOU DE ESTADO?',
       'REGIAO DE ORIGEM', 'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'NIVEL', 'Novo nível', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'COMPUTAÇÃO?'],
      dtype='object')

In [10]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Data columns (total 29 columns):
 #   Column                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                     --------------  -----
 0   ID                                                                                                                         4271 non-null   object
 1   IDADE                                                                                                                      4197 non-null   float64
 2   FAIXA IDADE                                                                                                                4271 non-null   object
 3   GENERO                                                                                                                     4262 non-null   object
 4   COR/RACA/ETNIA                                                                                                             4271 non-null   object
 5   PCD                                                                                                                        4271 non-null   object
 6   EXPERIENCIA_PROFISSIONAL_PREJUDICADA                                                                                       2190 non-null   object
 7   PREJUDICA?                                                                                                                 4271 non-null   bool
 8   ASPECTOS_PREJUDICADOS                                                                                                      837 non-null    object
 9   VIVE_NO_BRASIL                                                                                                             4271 non-null   bool
 10  ESTADO ONDE MORA                                                                                                           4156 non-null   object
 11  UF ONDE MORA                                                                                                               4156 non-null   object
 12  REGIAO ONDE MORA                                                                                                           4171 non-null   object
 13  MUDOU DE ESTADO?                                                                                                           4171 non-null   object
 14  REGIAO DE ORIGEM                                                                                                           772 non-null    object
 15  NIVEL DE ENSINO                                                                                                            4271 non-null   object
 16  ÁREA DE FORMAÇÃO                                                                                                           4149 non-null   object
 17  QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?                                                                                       4271 non-null   object
 18  SETOR                                                                                                                      3694 non-null   object
 19  NUMERO DE FUNCIONARIOS                                                                                                     3694 non-null   object
 20  GESTOR?                                                                                                                    3694 non-null   object
 21  CARGO COMO GESTOR                                                                                                          713 non-null    object
 22  CARGO ATUAL                                                                                                                2981 non-null   object
 23  NIVEL                                                                                                                      2981 non-null   object
 24  Novo nível                                                                                                                 3694 non-null   object
 25  FAIXA SALARIAL                                                                                                             3694 non-null   object
 26  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?                                                                     3694 non-null   object
 27  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?  3694 non-null   object
 28  COMPUTAÇÃO?                                                                                                                0 non-null      float64
dtypes: bool(2), float64(2), object(25)
memory usage: 909.4+ KB

In [12]:
dados.describe()

             IDADE  COMPUTAÇÃO?
count  4197.000000          0.0
mean     31.169168          NaN
std       6.902803          NaN
min      18.000000          NaN
25%      26.000000          NaN
50%      30.000000          NaN
75%      35.000000          NaN
max      54.000000          NaN